name: Upload To Test Pypi

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install package manager pipenv
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install pipenv

    - name: Create virtualenv
      run: |
        pipenv --python ${{ matrix.python-version }}

    - name: Build package
      run: pipenv build

    - name: Checks whether your distribution’s long description will render correctly on PyPI
      run: pipenv publish-conf-check

    - name: Publish Package
      env:
        USERNAME: ${{ secrets.PYPI_USERNAME }}
        PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pipenv publish -u $USERNAME -p $PASSWORD
