name: Upload Python Package

on:
  pull_request:
    branches: [ develop ]
    types: [ close ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install build twine

    - name: Build package
      run: python -m build

    - name: Checks whether your distribution’s long description will render correctly on PyPI
      run: twine check

    - name: Build and publish
      env:
        POETRY_USERNAME: ${{ secrets.PYPI_USERNAME }}
        POETRY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload -r testpypi dist/* -u $POETRY_USERNAME -p $POETRY_PASSWORD
