name: Python Test CI

on:
  pull_request:
    branches: [ release ]

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package manager pipenv and dependecies
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install pipenv tox-gh-actions

    - name: Create virtualenv
      run: |
        pipenv --python ${{ matrix.python-version }}

    - name: Run tox
      run: pipenv run tox


  package:
    name: Build package
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install package manager pipenv
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv sync --dev

    - name: Build package
      run: pipenv run build

    - name: Show result
      run: ls -l dist
